package com.example.socialk.model


data class Activity(
    val id: String,
    val title: String,
    val date: String,
    val start_time: String,
    val time_length: String,
    val creator_id: String,
    val description: String,
    val creator_username: String,
    val creator_name: String,
    var creator_profile_picture: String,
    var time_left: String,
    var end_time: String,
    var geoHash: Any?,
    var lat: Any?,
    var lng: Any?,
    var custom_location: String,
    val minUserCount: Int,
    val maxUserCount: Int,
    val disableChat: Boolean,
    val likes: Int,
    var invited_users: ArrayList<String>,
    val participants_profile_pictures: HashMap<String, String>,
    val participants_usernames: HashMap<String, String>,
    val creation_time: String,
    val location: String,
    val pictures: HashMap<String, String>,
    val enableActivitySharing: Boolean,
    val disablePictures: Boolean,
    val disableNotification: Boolean,
    val privateChat: Boolean,
    val public:Boolean,
    var participants_ids: ArrayList<String>,
    val awaitConfirmation:Boolean,
    var requests: ArrayList<String>,

    ) : java.io.Serializable {
    constructor() : this(
        id = "",
        title = "",
        date="",
        start_time="",
        time_length="",
        creator_id="",
        description="",
        creator_username="",
        creator_name="",
        creator_profile_picture="",
        time_left="",
        end_time="",
        geoHash=null,
        lat=null,
        lng=null,
        custom_location="",
        minUserCount= 0,
        maxUserCount=100,
        disableChat = false,
        likes=0,
        invited_users=ArrayList(),
        participants_profile_pictures=HashMap(),
        participants_usernames=HashMap(),
        creation_time="",
        location="",
        pictures=HashMap(),
        enableActivitySharing = false,
        disablePictures = false,
        disableNotification = false,
        privateChat = false,
        public=false,
         participants_ids =ArrayList(),
        awaitConfirmation=false,
        requests=ArrayList()
    )
}